### PR TITLE
connect Django with PostgreSQL

### PR DESCRIPTION
**Pull request by cindycaobutler**

### CODE REVIEW

**Comment by dawranliou** [comment]
Sorry I am picky here. But I feel the app name `backend` is too generic. It seems to me a hint of a monolithic application.

Here's a good article about [user registration / authentication using JWT](https://iheanyi.com/journal/user-registration-authentication-with-django-django-rest-framework-react-and-redux/). Under the Django project, the author named the app `accounts` and it handles the account actions and only. The urls were prefixed with `/users/`. In this case, not only could we simply plug his code into our project easily, but also easier to be reminded where the user related code is.

I propose the following apps to modularize the project:
-  app `accounts`/`users`: handles user registration and authentication.
- app `goal`: handles goal entities. This includes goal creation, subscription.

What do you think @cindycaobutler?

**Comment by dawranliou** [comment]
BTW, we better create a .gitignore for Python first ([example](https://github.com/github/gitignore/blob/master/Python.gitignore)). I see some .pyc files got committed.

**Comment by cindycaobutler** [comment]
Good ideas. Since you will work on user profile service, user auth needs to
be included into design. We will talk more about it on 1/21.




*Cindy Cao*
*Founder & President*

**Comment by cindycaobutler** [comment]
Ya, I haven't got time to push more code. Will do.

*Cindy Cao*
*Founder & President*

**Comment by cindycaobutler** [comment]
There is conflicts in settings.py. Can you please resolve conflicts?

**Comment by dawranliou** [comment]
I will take a look.

**Comment by dawranliou** [comment]
@cindycaobutler I need to be a collaborator in order to directly push the new commit to this branch.

**Comment by cindycaobutler** [comment]
Granted admin permission.

*Cindy Cao*
*Founder & President*

**Pull request merged**
