### PR TITLE
Background task infrastructure

### PR DESCRIPTION
**Pull request by dawranliou**
>  “Celery is an asynchronous task queue/job queue based on distributed message passing. It is focused on real-time operation, but supports scheduling as well.” 

Celery is widely used in Django projects to deal with async background jobs, such as periodic works or time consuming tasks. This PR adds Celery as an Django app and auto discover the async works when app launches.

This PR also introduced the dependency of Redis to serve as the async task message broker.

### CODE REVIEW

**Comment by dawranliou** [comment]
The tests for Python 3.7 was broken because of the dependency library - kombu. In Python 3.7 the word, async, becomes a keyword so it's not allowed to use it as variable name.

We could either:
1. Drop support and wait for official Python 3.7 releases, (it might still be broken then.)
1. Ignore the failure,
1. (I'm open to other suggestions.)

P.S. Python 3.7 is still in beta.

**Comment by BruceWeng** [comment]
Hi Randy,

Why are we upgrading python to 3.7? Is there any library not working in 3.6?

Best,
Bruce

On Tue, Apr 3, 2018 at 1:09 PM, Randy Daw-Ran Liou <notifications@github.com

**Comment by dawranliou** [comment]
@BruceWeng we are not upgrading to 3.7 at this point. All libraries are working in 3.6.

It's a general practice to forward support the newer Python versions because we don't want to be locked in to a particular version. As the newer versions of Python come out, we would have the flexibility to switch to the latest and greatest Python. Also, libraries might drop backward support slowly. No one could guarantee Python 3.6 will still be relevant in 10 years.

FYI the release we are waiting is: https://github.com/celery/kombu/pull/839

**Comment by dawranliou** [comment]
I tagged the nightly python version tests are allowed to fail. See:

https://travis-ci.org/MentorInTech/MIT_backend/builds/361887042?utm_source=github_status&utm_medium=notification

**Comment by dawranliou** [comment]
Look at #18 for an example usage

**Pull request merged**
